import { ref, watch } from 'vue'

const currentLanguage = ref(localStorage.getItem('yieldguard-lang') || 'en')

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Live Monitor',
    'nav.history': 'History',
    'nav.assistant': 'AI Assistant',
    'nav.map': 'Warehouse Map',
    'nav.settings': 'Settings',
    // Header
    'header.search': 'Select Warehouse / Zone',
    'header.notifications': 'Notifications',
    'header.clearAll': 'Clear All',
    'header.allOptimal': 'All systems optimal. No recent alerts.',
    // Auth
    'auth.back': 'Back to Website',
    'auth.backShort': 'Back',
    'auth.loginTitle': 'Log in to account',
    'auth.signupTitle': 'Create an account',
    'auth.resetTitle': 'Reset password',
    'auth.loginSub': 'Enter your details to access your dashboard.',
    'auth.signupSub': 'Start monitoring your storage environment today.',
    'auth.resetSub': 'We will send you instructions to reset your password.',
    'auth.updateTitle': 'Set new password',
    'auth.updateSub': 'Enter your new password below to secure your account.',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot Password?',
    'auth.btnLogin': 'Log In',
    'auth.btnSignup': 'Create Account',
    'auth.btnReset': 'Send Reset Link',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.orContinue': 'Or continue with',
    'auth.google': 'Sign in with Google',
    'auth.apple': 'Sign in with Apple',
    'auth.logout': 'Logout',
    'logout.confirm': 'Are you sure you want to sign out?',
    'logout.cancel': 'Cancel',
    'logout.signout': 'Sign Out',
    // Landing
    'landing.features': 'Features',
    'landing.founders': 'Founders',
    'landing.pricing': 'Pricing',
    'landing.testimonials': 'Testimonials',
    'landing.heroTitle.pre': 'Secure Your',
    'landing.heroHighlight': 'Coffee Yield',
    'landing.heroTitle.post': 'with Precision Analytics',
    'landing.heroSub': 'We provide a smart, automated sensor network to monitor temperature and humidity, ensuring your premium coffee beans never suffer from mold or drying.',
    'landing.getStarted': 'Get Started',
    'landing.howItWorks': 'How it Works',
    'landing.statsBeans': 'Beans Protected',
    'landing.statsSensors': 'Active Sensors',
    'landing.statsUptime': 'System Uptime',
    'landing.trustedBy': 'Trusted by Premium Coffee Exporters',
    'landing.ourProduct': 'Our Product',
    'landing.featuresTitle': 'Features That Ensure Quality',
    'landing.featuresSub': 'We combine hardware sensors with predictive AI to completely eliminate the guesswork from coffee bean storage.',
    'landing.monitorTitle': 'Easily Monitor The Overall Environment',
    'landing.monitorSub': 'Never wonder about the condition of your warehouse. Get real-time updates directly from the floor.',
    'landing.monitorCheck1': 'Track temperature & humidity instantly',
    'landing.monitorCheck2': 'View historical graphs to spot trends',
    'landing.learnMore': 'Learn More',
    'landing.aiTitle': 'Actionable AI Insights',
    'landing.aiSub': 'Our system doesn\'t just show numbers; it tells you exactly what to do. AI analyzes the data to prevent crop loss before it happens.',
    'landing.aiCheck1': 'Receive specific actions to take',
    'landing.aiCheck2': 'Voice-activated AI assistant',
    'landing.ourTeam': 'Our Team',
    'landing.meetFounders': 'Meet The Founders',
    'landing.foundersSub': 'The brilliant minds behind Yield Guard, dedicated to revolutionizing agricultural storage.',
    'landing.pricingTitle': 'Our Pricing',
    'landing.pricingOffer': 'Attractive Offers For Your Warehouse',
    'landing.pricingSub': 'Choose a plan that scales with your storage needs.',
    'landing.planStarter': 'Starter Pack',
    'landing.planPremium': 'Premium Package',
    'landing.planBusiness': 'Business Package',
    'landing.plan1Sensor': '1 Sensor Node',
    'landing.plan5Sensors': '5 Sensor Nodes',
    'landing.planUnlimitSensors': 'Unlimited Sensors',
    'landing.planBasicMonitor': 'Basic Monitoring',
    'landing.planAIAlerts': 'AI Predictive Alerts',
    'landing.planCustomAI': 'Custom AI Rules',
    'landing.plan24hHistory': '24hr Data History',
    'landing.planUnlimitHistory': 'Unlimited History',
    'landing.planSupport': '24/7 Priority Support',
    'landing.buyNow': 'Buy Now',
    'landing.startFree': 'Start Free',
    'landing.testimonialsTitle': 'Testimonials',
    'landing.testimonialsOffer': 'Various Positive Responses',
    'landing.testimonialsSub': 'Hear from warehouse managers who have secured their yields.',
    'landing.joinUs': 'Join Us Today',
    'landing.joinSub': 'Let\'s Use Our Services And Simplify Your Coffee Storage',
    'landing.startNow': 'Start Now',
    'landing.allRights': 'All rights reserved.',
    'landing.scrollToTop': 'Scroll to Top',
    'landing.roleCEO': 'Co-Founder & CEO',
    'landing.roleCTO': 'Co-Founder & CTO',
    'landing.roleEngineer': 'Co-Founder & Lead Engineer',
    'landing.roleAI': 'Co-Founder & AI Specialist',
    'landing.roleProduct': 'Co-Founder & Product Lead',
    'landing.testi1Name': 'Alexander Michael',
    'landing.testi1Role': 'Warehouse Manager',
    'landing.testi1Text': 'This platform has become my favorite. The AI insights make it so easy for me to protect all my coffee beans and prevent mold. Very good service!',
    'landing.testi2Name': 'Sarah Jenkins',
    'landing.testi2Role': 'Quality Control Lead',
    'landing.testi2Text': 'Yield Guard completely transformed our operations. We no longer rely on manual checks, and the predictive alerts are scarily accurate.',
    'landing.testi3Name': 'David Ochola',
    'landing.testi3Role': 'Logistics Director',
    'landing.testi3Text': 'The return on investment was visible in the first month. By maintaining strict environmental controls, our premium yield remained untouched.',
    // Settings
    'settings.title': 'System Settings',
    'settings.sub': 'Configure alerts and environmental thresholds',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved!',
    'settings.thresholds': 'Environmental Thresholds',
    'settings.thresholdsSub': 'These values determine when the hardware ESP32 triggers alerts. Currently, these are interface-only and must match your flashed hardware constants.',
    'settings.alerts': 'Alert Preferences',
    'settings.langPrefs': 'Language Preferences',
    'settings.dashLang': 'Dashboard Language',
    'settings.dashLangSub': 'Select your preferred language for the interface.',
    // Dashboard
    'dash.liveSensors': 'Live Sensors',
    'dash.systemLive': 'System Live',
    'dash.systemOffline': 'System Offline',
    'dash.export': 'Export',
    'dash.timeframe': 'Timeframe',
    'dash.last24h': 'Last 24 Hours',
    'dash.last7d': 'Last 7 Days',
    'dash.last30d': 'Last 30 Days',
    'dash.downloadCSV': 'Download CSV',
    'dash.downloadPDF': 'Download PDF',
    // MetricCard
    'card.airTemp': 'Air Temperature',
    'card.relHumidity': 'Relative Humidity',
    'card.temperature': 'Temperature',
    'card.humidity': 'Humidity',
    'card.optimalMin': 'Optimal Min',
    'card.optimalMax': 'Optimal Max',
    'card.danger': 'Danger',
    'card.warning': 'Warning',
    'card.normal': 'Normal',
    // ConditionChart
    'chart.title': '72h Detailed Warehouse Conditions',
    'chart.temp': 'Temp',
    'chart.humidity': 'Humidity',
    // History
    'history.title': 'System History',
    'history.sub': 'Historical logs and environmental trends',
    'history.envData': 'Environmental Data',
    'history.envDataSub': 'Historical logs export',
    'history.alertLogs': 'Alert Event Logs',
    'history.alertLogsSub': 'Historical alerts export',
    'history.conditionTrends': '72-Hour Condition Trends',
    'history.liveUpdating': 'Live Updating',
    'history.alertEventLog': 'Alert Event Log',
    'history.records': 'Records',
    'history.time': 'Time',
    'history.eventType': 'Event Type',
    'history.message': 'Message',
    'history.systemAlert': 'System Alert',
    'history.noAlerts': 'No historical alerts recorded. Systems have remained optimal.',
    // WarehouseMap
    'map.title': 'Warehouse Map',
    'map.sub': 'Facility Overview & Zone Monitoring',
    'map.selectZone': 'Select Zone',
    'map.floorplan': 'Interactive Floorplan',
    'map.activeSensor': 'Active Sensor',
    'map.geoLocation': 'Geographic Location',
    'map.liveGPS': 'Live GPS Tracking',
    'map.zoneA.name': 'Zone A',
    'map.zoneA.sub': 'Main Coffee Storage',
    'map.zoneB.name': 'Zone B',
    'map.zoneB.sub': 'Sorting & Processing',
    'map.zoneC.name': 'Zone C',
    'map.zoneC.sub': 'Packaging',
    'map.liveData': 'Live Data',
    'map.waitingData': 'Waiting for data...',
    'map.offline': 'Offline / No Sensor',
    // AI Assistant
    'ai.title': 'Yield Guard AI',
    'ai.sub': 'Predictive Environmental Intelligence',
    'ai.welcome': 'Welcome to the full AI Assistant dashboard. I have full access to your warehouse sensor data. Ask me anything about environmental safety or predictive risks!',
    'ai.placeholder': 'Ask AI...',
    'ai.listening': 'Listening...',
    // ActionNotification
    'popup.action': 'Action',
    // Profile
    'profile.title': 'Your Profile',
    'profile.subtitle': 'Manage your personal information',
    'profile.back': 'Back',
    'profile.email': 'Email Address',
    'profile.emailSub': 'Email cannot be changed from this profile settings.',
    'profile.fullName': 'Full Name',
    'profile.fullNamePlaceholder': 'Enter your full name',
    'profile.phone': 'Phone Number',
    'profile.phonePlaceholder': 'Enter phone number',
    'profile.save': 'Save Profile',
    'profile.saving': 'Saving Changes...',
    'profile.success': 'Profile updated successfully!',
    'profile.error': 'Failed to update profile. Please try again.',
  },
  lg: {
    // Navigation
    'nav.dashboard': 'Ebigobererwa (Monitor)',
    'nav.history': 'Ebyakayita',
    'nav.assistant': 'Amagezi g\'Ekyuma (AI)',
    'nav.map': 'Maapu Y\'Eterekero',
    'nav.settings': 'Enteekateeka',
    // Header
    'header.search': 'Londa Eterekero / Ekitundu',
    'header.notifications': 'Okutegeezebwa',
    'header.clearAll': 'Ggyawo Byonna',
    'header.allOptimal': 'Byonna bitambula bulungi. Tewali buzibu.',
    // Auth
    'auth.back': 'Dda ku Muko',
    'auth.backShort': 'Dda Mabega',
    'auth.loginTitle': 'Yingira mu Akawunti',
    'auth.signupTitle': 'Kola Akawunti',
    'auth.resetTitle': 'Zzaawo Ebisumuluzo',
    'auth.loginSub': 'Yingiza ebikukwatako okutuuka ku dashboard yo.',
    'auth.signupSub': 'Tandika okulondoola embera z\'eterekero lyo leero.',
    'auth.resetSub': 'Tujja kukuweereza obubaka obuzzaawo ebisumuluzo.',
    'auth.updateTitle': 'Teekako ekisumuluzo ekipya',
    'auth.updateSub': 'Yingiza ekisumuluzo kyo ekipya wammanga.',
    'auth.fullName': 'Amanya Mampuyi',
    'auth.email': 'Ennamba ya Email',
    'auth.password': 'Ekisumuluzo',
    'auth.forgot': 'Oyerabidde Ekisumuluzo?',
    'auth.btnLogin': 'Yingira',
    'auth.btnSignup': 'Kola Akawunti',
    'auth.btnReset': 'Saba Ebisumuluzo Ebigya',
    'auth.noAccount': 'Tolina akawunti?',
    'auth.hasAccount': 'Olina akawunti edda?',
    'auth.orContinue': 'Oba yingira ne',
    'auth.google': 'Yingira ne Google',
    'auth.apple': 'Yingira ne Apple',
    'auth.logout': 'Fuluma',
    'logout.confirm': 'Oli mukakafu nti oyagala okufuluma?',
    'logout.cancel': 'Sazamu',
    'logout.signout': 'Fuluma',
    // Landing
    'landing.features': 'Ebirimu',
    'landing.founders': 'Abaatandikawo',
    'landing.pricing': 'Ebisale',
    'landing.testimonials': 'Obujulizi',
    'landing.heroTitle.pre': 'Kuuma Ebirime byo',
    'landing.heroHighlight': 'eby\'Emmwaanyi',
    'landing.heroTitle.post': 'N\'amagezi',
    'landing.heroSub': 'Tuwaayo ebyuma ebikebera obunnyogovu n\'ebbugumu okukakasa nti emmwaanyi zo teziyonooneka nga zivunda oba okukala ennyo.',
    'landing.getStarted': 'Tandika Kati',
    'landing.howItWorks': 'Engeri Gye Kikolamu',
    'landing.statsBeans': 'Emmwaanyi Eziwoneddwa',
    'landing.statsSensors': 'Ebyuma Ebikola',
    'landing.statsUptime': 'Obudde bw\'Okukola',
    'landing.trustedBy': 'Abatutwala mu maaso mu kutunda emmwaanyi',
    'landing.ourProduct': 'Ekyuma Kye Tukola',
    'landing.featuresTitle': 'Ebirungi ebikuuma omutindo',
    'landing.featuresSub': 'Tukozesa ebyuma ne AI okukukwasiza okukuuma emmwaanyi zo.',
    'landing.monitorTitle': 'Laba embeera y\'eterekero lyo mangu',
    'landing.monitorSub': 'Obujjukivu ku mbeera y\'eterekero lyo ssaawa yonna.',
    'landing.monitorCheck1': 'Goberera ebbugumu n\'obunnyogovu mangu',
    'landing.monitorCheck2': 'Laba ennamba n\'ebifaananyi okubijjukira',
    'landing.learnMore': 'Yiga Ebisingawo',
    'landing.aiTitle': 'Amagezi ga AI amangu',
    'landing.aiSub': 'AI eyiga ebirina okukolwa okukinga okufiirwa ebirime.',
    'landing.aiCheck1': 'Funa ebiragiro eby\'okukola mangu',
    'landing.aiCheck2': 'Amagezi ga AI agakozesa eddoboozi',
    'landing.ourTeam': 'Ttiimu Yaffe',
    'landing.meetFounders': 'Laba Abaatandikawo',
    'landing.foundersSub': 'Abaatandika Yield Guard okukyusa obunibi.',
    'landing.pricingTitle': 'Ebisale Byaffe',
    'landing.pricingOffer': 'Ebisale ebirungi eri eterekero lyo',
    'landing.pricingSub': 'Londa enteekateeka ekwasizako obwetaavu bwo.',
    'landing.planStarter': 'Enteekateeka Entandikwa',
    'landing.planPremium': 'Enteekateeka ya Waggulu',
    'landing.planBusiness': 'Enteekateeka ya Bizinesi',
    'landing.plan1Sensor': 'Ekyuma 1',
    'landing.plan5Sensors': 'Ebyuma 5',
    'landing.planUnlimitSensors': 'Ebyuma Ebisingawo',
    'landing.planBasicMonitor': 'Okulaba okw\'abulijjo',
    'landing.planAIAlerts': 'AI ewa endabula',
    'landing.planCustomAI': 'AI gy\'oteekako ebiragiro byo',
    'landing.plan24hHistory': 'Ebyakayita mu ssaawa 24',
    'landing.planUnlimitHistory': 'Ebyakayita ebingi',
    'landing.planSupport': 'Okubayamba ssaawa 24',
    'landing.buyNow': 'Gula Kati',
    'landing.startFree': 'Tandika ku bwereere',
    'landing.testimonialsTitle': 'Obujulizi',
    'landing.testimonialsOffer': 'Okuddamu okungi okulungi',
    'landing.testimonialsSub': 'Wulira okuva ku balabirira amaterekero abakuuma emmwaanyi zaabwe.',
    'landing.joinUs': 'Yegatte naffe leero',
    'landing.joinSub': 'Kozesa empeereza zaffe oyongeze obungi bw\'emmwaanyi zo',
    'landing.startNow': 'Tandika Kati',
    'landing.allRights': 'Byonna biri mu mateeka.',
    'landing.scrollToTop': 'Dda waggulu',
    'landing.roleCEO': 'Abaatandikawo & CEO',
    'landing.roleCTO': 'Abaatandikawo & CTO',
    'landing.roleEngineer': 'Abaatandikawo & Lead Engineer',
    'landing.roleAI': 'Abaatandikawo & AI Specialist',
    'landing.roleProduct': 'Abaatandikawo & Product Lead',
    'landing.testi1Name': 'Alexander Michael',
    'landing.testi1Role': 'Mumanegya w\'Eterekero',
    'landing.testi1Text': 'Enkola eno efuuse gye nsinga okwagala. AI enyambye nnyo okukuuma emmwaanyi zange zonna ne nkinga okuvunda. Empeereza nnungi nnyo!',
    'landing.testi2Name': 'Sarah Jenkins',
    'landing.testi2Role': 'Omukulu w\'Omutindo',
    'landing.testi2Text': 'Yield Guard ekyusizza nnyo engeri gye tukolamu. Tetukyakozesa mikkono gyokka, ssaako endabula za AI ntuufu nnyo.',
    'landing.testi3Name': 'David Ochola',
    'landing.testi3Role': 'Omukulu w\'Entambula',
    'landing.testi3Text': 'Amagoba gaalabyeko mu mwezi ogwasooka. Mu kukuuma embeera y\'eterekero, emmwaanyi zaffe tezaayonoonesebwa.',
    // Settings
    'settings.title': 'Enteekateeka z\'Ebyuma',
    'settings.sub': 'Teekawo endabula n\'obungi bw\'ebbugumu/obunnyogovu',
    'settings.save': 'Kuumayo',
    'settings.saving': 'Tereka...',
    'settings.saved': 'Kiterekeddwa!',
    'settings.thresholds': 'Enteekateeka z\'Ebbugumu',
    'settings.thresholdsSub': 'Bino byebipima bya ESP32 ebiwa endabula.',
    'settings.alerts': 'Enteekateeka z\'Endabula',
    'settings.langPrefs': 'Enteekateeka z\'Olwimi',
    'settings.dashLang': 'Olwimi lwa Dashboard',
    'settings.dashLangSub': 'Londa olwimi lw\'osinga okwagala.',
    // Dashboard
    'dash.liveSensors': 'Ebyuma Ebikola',
    'dash.systemLive': 'Ekyuma Kiriwo',
    'dash.systemOffline': 'Ekyuma Kizimye',
    'dash.export': 'Samu',
    'dash.timeframe': 'Obudde',
    'dash.last24h': 'Essawa 24 Eziyise',
    'dash.last7d': 'Ennaku 7 Eziyise',
    'dash.last30d': 'Ennaku 30 Eziyise',
    'dash.downloadCSV': 'Kukulawo CSV',
    'dash.downloadPDF': 'Kukulawo PDF',
    // MetricCard
    'card.airTemp': 'Ebbugumu y\'Empewo',
    'card.relHumidity': 'Obunnyogovu',
    'card.temperature': 'Ebbugumu',
    'card.humidity': 'Obunnyogovu',
    'card.optimalMin': 'Obunono Obwenkana',
    'card.optimalMax': 'Obukulu Obwenkana',
    'card.danger': 'Akabi',
    'card.warning': 'Okulabula',
    'card.normal': 'Bulungi',
    // ConditionChart
    'chart.title': 'Embeera y\'Eterekero mu Essawa 72',
    'chart.temp': 'Ebbugumu',
    'chart.humidity': 'Obunnyogovu',
    // History
    'history.title': 'Ebyakayita by\'Ekyuma',
    'history.sub': 'Ebiwandiiko n\'emirundi gy\'embeera',
    'history.envData': 'Ebikwata ku Mbeera',
    'history.envDataSub': 'Samu ebikwata ku mbeera',
    'history.alertLogs': 'Ebiwandiiko by\'Endabula',
    'history.alertLogsSub': 'Samu endabula eziyise',
    'history.conditionTrends': 'Embeera mu Essawa 72',
    'history.liveUpdating': 'Kikola Kaakano',
    'history.alertEventLog': 'Ebiwandiiko by\'Endabula',
    'history.records': 'Ebiwandiiko',
    'history.time': 'Obudde',
    'history.eventType': 'Engeri y\'Ensonga',
    'history.message': 'Obubaka',
    'history.systemAlert': 'Endabula y\'Ekyuma',
    'history.noAlerts': 'Tewali ndabula yazibikibwa. Byonna byali bimala.',
    // WarehouseMap
    'map.title': 'Maapu y\'Eterekero',
    'map.sub': 'Ekyegattirwa n\'Okulabirira Ebikitundu',
    'map.selectZone': 'Londa Ekitundu',
    'map.floorplan': 'Maapu Enkola',
    'map.activeSensor': 'Ekyuma Ekikola',
    'map.geoLocation': 'Ekifo ku Nsi',
    'map.liveGPS': 'GPS Ekola Kaakano',
    'map.zoneA.name': 'Ekitundu A',
    'map.zoneA.sub': 'Okutereka Emmwaanyi',
    'map.zoneB.name': 'Ekitundu B',
    'map.zoneB.sub': 'Okusalula n\'Okukolera',
    'map.zoneC.name': 'Ekitundu C',
    'map.zoneC.sub': 'Okusindika',
    'map.liveData': 'Ebikwatibwa Kaakano',
    'map.waitingData': 'Gw\'eteesa amakuru...',
    'map.offline': 'Kizimye / Tewali Kyuma',
    // AI Assistant
    'ai.title': 'Amagezi ga Yield Guard',
    'ai.sub': 'Ebiragiro eby\'Embeera eby\'Ensonga',
    'ai.welcome': 'Tukuwa mu kibirafu ky\'AI Assistant. Ndina okufuna ebikwata ku byuma byonna by\'eterekero lyo. Buuza ekintu kyonna ekyakutwaza okukuuma emmwaanyi!',
    'ai.placeholder': 'Buuza AI...',
    'ai.listening': 'Nkuwuliriza...',
    // ActionNotification
    'popup.action': 'Okolera',
    // Profile
    'profile.title': 'Ebikukwatako',
    'profile.subtitle': 'Labirira ebikukwatako mangu',
    'profile.back': 'Dda Mabega',
    'profile.email': 'Ennamba ya Email',
    'profile.emailSub': 'Email teyinza kukyusibwa okuva wano.',
    'profile.fullName': 'Amanya Mampuyi',
    'profile.fullNamePlaceholder': 'Yingiza amanya go',
    'profile.phone': 'Ennamba y\'Essimu',
    'profile.phonePlaceholder': 'Yingiza ennamba y\'essimu',
    'profile.save': 'Tereka Ebikukwatako',
    'profile.saving': 'Biterekebwa...',
    'profile.success': 'Ebikukwatako biterekeddwa bulungi!',
    'profile.error': 'Okutereka kulemye. Gezaako nate.',
  },
  sw: {
    // Navigation
    'nav.dashboard': 'Ufuatiliaji',
    'nav.history': 'Historia',
    'nav.assistant': 'Msaidizi wa AI',
    'nav.map': 'Ramani ya Ghala',
    'nav.settings': 'Mipangilio',
    // Header
    'header.search': 'Chagua Ghala / Sehemu',
    'header.notifications': 'Arifa',
    'header.clearAll': 'Futa Zote',
    'header.allOptimal': 'Mifumo yote iko sawa. Hakuna arifa mpya.',
    // Auth
    'auth.back': 'Rudi kwa Tovuti',
    'auth.backShort': 'Nyuma',
    'auth.loginTitle': 'Ingia kwenye akaunti',
    'auth.signupTitle': 'Fungua akaunti',
    'auth.resetTitle': 'Weka upya nenosiri',
    'auth.loginSub': 'Ingiza maelezo yako kufikia dashibodi yako.',
    'auth.signupSub': 'Anza kufuatilia mazingira ya ghala lako leo.',
    'auth.resetSub': 'Tutakutumia maelekezo ya kuweka upya nenosiri.',
    'auth.updateTitle': 'Weka nenosiri jipya',
    'auth.updateSub': 'Ingiza nenosiri lako jipya hapa chini.',
    'auth.fullName': 'Jina Kamili',
    'auth.email': 'Barua Pepe',
    'auth.password': 'Nenosiri',
    'auth.forgot': 'Umesahau Nenosiri?',
    'auth.btnLogin': 'Ingia',
    'auth.btnSignup': 'Fungua Akaunti',
    'auth.btnReset': 'Tuma Kiungo',
    'auth.noAccount': 'Hauna akaunti?',
    'auth.hasAccount': 'Tayari una akaunti?',
    'auth.orContinue': 'Au endelea na',
    'auth.google': 'Ingia na Google',
    'auth.apple': 'Ingia na Apple',
    'auth.logout': 'Ondoka',
    'logout.confirm': 'Je, una uhakika unataka kuondoka?',
    'logout.cancel': 'Ghairi',
    'logout.signout': 'Ondoka',
    // Landing
    'landing.features': 'Vipengele',
    'landing.founders': 'Waanzilishi',
    'landing.pricing': 'Bei',
    'landing.testimonials': 'Ushuhuda',
    'landing.heroTitle.pre': 'Linda',
    'landing.heroHighlight': 'Mavuno yako ya Kahawa',
    'landing.heroTitle.post': 'kwa Uchambuzi Sahihi',
    'landing.heroSub': 'Tunatoa mtandao wa sensa kufuatilia joto na unyevu, kuhakikisha kahawa yako haiharibiki kwa ukungu au kukauka sana.',
    'landing.getStarted': 'Anza Sasa',
    'landing.howItWorks': 'Jinsi Inavyofanya Kazi',
    'landing.statsBeans': 'Kahawa Iliyolindwa',
    'landing.statsSensors': 'Sensa Zinazofanya Kazi',
    'landing.statsUptime': 'Muda wa Kufanya Kazi',
    'landing.trustedBy': 'Inaaminiwa na Wasafirishaji Wakuu wa Kahawa',
    'landing.ourProduct': 'Bidhaa Yetu',
    'landing.featuresTitle': 'Vipengele Vinavyohakikisha Ubora',
    'landing.featuresSub': 'Tunachanganya sensa za vifaa na AI ya utabiri ili kuondoa kabisa kubahatisha katika uhifadhi wa kahawa.',
    'landing.monitorTitle': 'Fuatilia Mazingira ya Jumla kwa Urahisi',
    'landing.monitorSub': 'Usiwahi kushangaa juu ya hali ya ghala lako. Pata sasisho za wakati halisi moja kwa moja kutoka ghalani.',
    'landing.monitorCheck1': 'Fuatilia joto na unyevu papo hapo',
    'landing.monitorCheck2': 'Angalia grafu za kihistoria ili kuona mienendo',
    'landing.learnMore': 'Jifunze Zaidi',
    'landing.aiTitle': 'Ufahamu wa AI Unaoweza Kuchukuliwa Hatua',
    'landing.aiSub': 'Mfumo wetu hauonyeshi namba tu; unakuambia nini hasa cha kufanya. AI huchambua data ili kuzuia upotevu wa mazao.',
    'landing.aiCheck1': 'Pokea hatua maalum za kuchukua',
    'landing.aiCheck2': 'Msaidizi wa AI anayeendeshwa na sauti',
    'landing.ourTeam': 'Timu Yetu',
    'landing.meetFounders': 'Kutana na Waanzilishi',
    'landing.foundersSub': 'Watu wenye akili nyuma ya Yield Guard, waliojitolea kuleta mapinduzi katika uhifadhi wa kilimo.',
    'landing.pricingTitle': 'Bei Zetu',
    'landing.pricingOffer': 'Ofa za Kuvutia kwa Ghala Lako',
    'landing.pricingSub': 'Chagua mpango unaoendana na mahitaji yako ya uhifadhi.',
    'landing.planStarter': 'Pakiti ya Kuanzia',
    'landing.planPremium': 'Pakiti ya Premium',
    'landing.planBusiness': 'Pakiti ya Biashara',
    'landing.plan1Sensor': 'Sensa 1',
    'landing.plan5Sensors': 'Sensa 5',
    'landing.planUnlimitSensors': 'Sensa zisizo na kikomo',
    'landing.planBasicMonitor': 'Ufuatiliaji wa Msingi',
    'landing.planAIAlerts': 'Arifa za Utabiri wa AI',
    'landing.planCustomAI': 'Sheria Maalum za AI',
    'landing.plan24hHistory': 'Historia ya Data ya Saa 24',
    'landing.planUnlimitHistory': 'Historia isiyo na kikomo',
    'landing.planSupport': 'Msaada wa Kipaumbele wa 24/7',
    'landing.buyNow': 'Nunua Sasa',
    'landing.startFree': 'Anza Bure',
    'landing.testimonialsTitle': 'Ushuhuda',
    'landing.testimonialsOffer': 'Majibu Mbalimbali Chanya',
    'landing.testimonialsSub': 'Sikia kutoka kwa wasimamizi wa ghala ambao wamelinda mazao yao.',
    'landing.joinUs': 'Jiunge Nasi Leo',
    'landing.joinSub': 'Tutumie Huduma Zetu na Kurahisisha Uhifadhi Wako wa Kahawa',
    'landing.startNow': 'Anza Sasa',
    'landing.allRights': 'Haki zote zimehifadhiwa.',
    'landing.scrollToTop': 'Rudi Juu',
    'landing.roleCEO': 'Mwanzilishi & CEO',
    'landing.roleCTO': 'Mwanzilishi & CTO',
    'landing.roleEngineer': 'Mwanzilishi & Mhandisi Mkuu',
    'landing.roleAI': 'Mwanzilishi & Mtaalam wa AI',
    'landing.roleProduct': 'Mwanzilishi & Kiongozi wa Bidhaa',
    'landing.testi1Name': 'Alexander Michael',
    'landing.testi1Role': 'Meneja wa Ghala',
    'landing.testi1Text': 'Jukwaa hili limekuwa kipenzi changu. Ufahamu wa AI hufanya iwe rahisi kwangu kulinda kahawa yangu yote na kuzuia ukungu. Huduma nzuri sana!',
    'landing.testi2Name': 'Sarah Jenkins',
    'landing.testi2Role': 'Kiongozi wa Udhibiti wa Ubora',
    'landing.testi2Text': 'Yield Guard imebadilisha kabisa shughuli zetu. Hatutegemei tena ukaguzi wa mwongozo, na arifa za utabiri ni sahihi sana.',
    'landing.testi3Name': 'David Ochola',
    'landing.testi3Role': 'Mkurugenzi wa Usafirishaji',
    'landing.testi3Text': 'Faida ilionekana katika mwezi wa kwanza. Kwa kudumisha udhibiti mkali wa mazingira, mavuno yetu bora yalibaki bila kuguswa.',
    // Settings
    'settings.title': 'Mipangilio ya Mfumo',
    'settings.sub': 'Sanidi arifa na mipaka ya mazingira',
    'settings.save': 'Hifadhi',
    'settings.saving': 'Inahifadhi...',
    'settings.saved': 'Imehifadhiwa!',
    'settings.thresholds': 'Mipaka ya Mazingira',
    'settings.thresholdsSub': 'Maadili haya yanaamua wakati ESP32 inaleta arifa.',
    'settings.alerts': 'Mapendeleo ya Arifa',
    'settings.langPrefs': 'Mapendeleo ya Lugha',
    'settings.dashLang': 'Lugha ya Dashibodi',
    'settings.dashLangSub': 'Chagua lugha unayopendelea kwa kiolesura.',
    // Dashboard
    'dash.liveSensors': 'Sensa Zinazofanya Kazi',
    'dash.systemLive': 'Mfumo Unaofanya Kazi',
    'dash.systemOffline': 'Mfumo Umezima',
    'dash.export': 'Hamisha',
    'dash.timeframe': 'Muda',
    'dash.last24h': 'Masaa 24 Yaliyopita',
    'dash.last7d': 'Siku 7 Zilizopita',
    'dash.last30d': 'Siku 30 Zilizopita',
    'dash.downloadCSV': 'Pakua CSV',
    'dash.downloadPDF': 'Pakua PDF',
    // MetricCard
    'card.airTemp': 'Joto la Hewa',
    'card.relHumidity': 'Unyevu wa Hewa',
    'card.temperature': 'Joto',
    'card.humidity': 'Unyevu',
    'card.optimalMin': 'Kiwango cha Chini',
    'card.optimalMax': 'Kiwango cha Juu',
    'card.danger': 'Hatari',
    'card.warning': 'Onyo',
    'card.normal': 'Kawaida',
    // ConditionChart
    'chart.title': 'Hali ya Ghala kwa Masaa 72',
    'chart.temp': 'Joto',
    'chart.humidity': 'Unyevu',
    // History
    'history.title': 'Historia ya Mfumo',
    'history.sub': 'Kumbukumbu na mwenendo wa mazingira',
    'history.envData': 'Data ya Mazingira',
    'history.envDataSub': 'Hamisha kumbukumbu za mazingira',
    'history.alertLogs': 'Kumbukumbu za Arifa',
    'history.alertLogsSub': 'Hamisha arifa zilizopita',
    'history.conditionTrends': 'Mwenendo wa Hali kwa Masaa 72',
    'history.liveUpdating': 'Inasasisha Moja kwa Moja',
    'history.alertEventLog': 'Kumbukumbu za Arifa',
    'history.records': 'Rekodi',
    'history.time': 'Wakati',
    'history.eventType': 'Aina ya Tukio',
    'history.message': 'Ujumbe',
    'history.systemAlert': 'Arifa ya Mfumo',
    'history.noAlerts': 'Hakuna arifa zilizorekodiwa. Mifumo imekuwa bora.',
    // WarehouseMap
    'map.title': 'Ramani ya Ghala',
    'map.sub': 'Muhtasari wa Kituo na Ufuatiliaji wa Kanda',
    'map.selectZone': 'Chagua Kanda',
    'map.floorplan': 'Ramani ya Sakafu',
    'map.activeSensor': 'Sensa Inayofanya Kazi',
    'map.geoLocation': 'Mahali pa Kijiografia',
    'map.liveGPS': 'Ufuatiliaji wa GPS Moja kwa Moja',
    'map.zoneA.name': 'Kanda A',
    'map.zoneA.sub': 'Uhifadhi Mkuu wa Kahawa',
    'map.zoneB.name': 'Kanda B',
    'map.zoneB.sub': 'Upangaji na Usindikaji',
    'map.zoneC.name': 'Kanda C',
    'map.zoneC.sub': 'Ufungaji',
    'map.liveData': 'Data ya Sasa',
    'map.waitingData': 'Inasubiri data...',
    'map.offline': 'Imezima / Hakuna Sensa',
    // AI Assistant
    'ai.title': 'AI ya Yield Guard',
    'ai.sub': 'Akili ya Mazingira ya Utabiri',
    'ai.welcome': 'Karibu kwenye dashibodi kamili ya Msaidizi wa AI. Nina ufikiaji kamili wa data ya sensa za ghala lako. Niulize chochote kuhusu usalama wa mazingira au hatari za utabiri!',
    'ai.placeholder': 'Uliza AI...',
    'ai.listening': 'Ninakusikiliza...',
    // ActionNotification
    'popup.action': 'Hatua',
    // Profile
    'profile.title': 'Wasifu Wako',
    'profile.subtitle': 'Simamia maelezo yako ya kibinafsi',
    'profile.back': 'Nyuma',
    'profile.email': 'Barua Pepe',
    'profile.emailSub': 'Barua pepe haiwezi kubadilishwa hapa.',
    'profile.fullName': 'Jina Kamili',
    'profile.fullNamePlaceholder': 'Ingiza jina lako kamili',
    'profile.phone': 'Namba ya Simu',
    'profile.phonePlaceholder': 'Ingiza namba ya simu',
    'profile.save': 'Hifadhi Wasifu',
    'profile.saving': 'Inahifadhi...',
    'profile.success': 'Wasifu umesasishwa kikamilifu!',
    'profile.error': 'Imeshindwa kusasisha wasifu. Tafadhali jaribu tena.',
  }
}

export function useLanguage() {
  const setLanguage = (lang) => {
    if (['en', 'lg', 'sw'].includes(lang)) {
      currentLanguage.value = lang
    }
  }

  const t = (key) => {
    const lang = currentLanguage.value || 'en'
    return translations[lang]?.[key] || translations['en']?.[key] || key
  }

  // Persist language to localStorage
  watch(currentLanguage, (newLang) => {
    localStorage.setItem('yieldguard-lang', newLang)
  })

  return {
    currentLanguage,
    setLanguage,
    t,
    languages: [
      { code: 'en', name: 'English', short: 'EN' },
      { code: 'lg', name: 'Luganda', short: 'LG' },
      { code: 'sw', name: 'Swahili', short: 'SW' }
    ]
  }
}
